

import java.awt.BorderLayout;
import java.awt.Graphics;
import java.awt.GridLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author SHKIM
 */
public class MainFrame extends javax.swing.JFrame {
    
    
    private Image backgroundImage;
    
    /**
     * Creates new form MainFrame
     */
    public MainFrame() {
        initComponents();
        //setBackgroundImage();
       
        
        koreanFood.addActionListener(new java.awt.event.ActionListener() {
        @Override
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            koreanFoodActionPerformed(evt);
        }
        
        
    });
    }
    private void setBackgroundImage() {
        // 배경 이미지를 불러와서 ImageIcon을 생성
        ImageIcon backgroundImageIcon = new ImageIcon(getClass().getResource("/background.jpg"));

        //ImageIcon에서 Image 추출
        backgroundImage = backgroundImageIcon.getImage();
        
        
    }
    
    // JFrame의 contentPane에 배경 이미지를 그리는 메서드
    @Override
    public void paint(Graphics g) {
        // 기본적인 그리기 작업 수행
        super.paint(g);

        // 배경 이미지를 그린다.
        g.drawImage(backgroundImage, 0, 0, getWidth(), getHeight(), this);
    }
    
   private void addMenuToSelectedMenu(String menuNameAndPrice) {
    // Extract the menu name before the space
    String menuName = menuNameAndPrice.substring(0, menuNameAndPrice.indexOf(' '));

    String currentText = selectedMenu.getText();
    if (currentText.isEmpty()) {
        selectedMenu.setText(menuName);
    } else {
        selectedMenu.setText(currentText + ", " + menuName);
    }
}
   
   private void addPriceToTotalPay(String menuNameAndPrice){
        // Extract the price after the space (remove non-numeric characters)
    String priceString = menuNameAndPrice.replaceAll("[^0-9]", "");

    // Check if the priceString is not empty after removing non-numeric characters
    if (!priceString.isEmpty()) {
        try {
            int price = Integer.parseInt(priceString);

            // Add the price to totalPay
            int currentTotalPay = Integer.parseInt(totalPay.getText());
            int newTotalPay = currentTotalPay + price;
            totalPay.setText(Integer.toString(newTotalPay) );
        } catch (NumberFormatException e) {
            // Handle the exception (print or log the error, or take appropriate action)
            System.err.println("Error parsing price: " + e.getMessage());
        }
    } else {
        // Handle the case where priceString is empty
        System.err.println("Empty price string");
    }


   }
   
   private void addMenuItem(JPanel panel, String menuName, String price, String imagePath) {
    // Create a panel for each menu item
    JPanel menuItemPanel = new JPanel(new BorderLayout());

    // Add menu image to the panel
    ImageIcon icon = new ImageIcon(getClass().getResource(imagePath));
    JLabel menuImage = new JLabel(new ImageIcon(icon.getImage().getScaledInstance(90, 90, Image.SCALE_DEFAULT)));
    menuItemPanel.add(menuImage, BorderLayout.WEST);

    // Add menu name and price to the panel
    JLabel menuLabel = new JLabel(menuName + " " + price);
    menuItemPanel.add(menuLabel, BorderLayout.CENTER);

    // Add the menu item panel to the main panel
    panel.add(menuItemPanel);
}
     
   private void resetOrderDetails(){
       selectedMenu.setText("");
       totalPay.setText("0");
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        menu1 = new javax.swing.JLabel();
        menu2 = new javax.swing.JLabel();
        menu3 = new javax.swing.JLabel();
        menu4 = new javax.swing.JLabel();
        menu1NameAndPrice = new javax.swing.JLabel();
        menu2NameAndPrice = new javax.swing.JLabel();
        menu3NameAndPrice = new javax.swing.JLabel();
        menu4NameAndPrice = new javax.swing.JLabel();
        selectedMenu = new javax.swing.JTextField();
        orderMenu = new javax.swing.JButton();
        koreanFood = new javax.swing.JButton();
        japaneseFood = new javax.swing.JButton();
        chineseFood = new javax.swing.JButton();
        drinkMenu = new javax.swing.JButton();
        allMenu = new javax.swing.JButton();
        orderedMenu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblTotalPay = new javax.swing.JLabel();
        lblSelectedMenu = new javax.swing.JLabel();
        totalPay = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        menu1.setToolTipText("");
        menu1.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menu1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu1MouseClicked(evt);
            }
        });

        menu2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu2MouseClicked(evt);
            }
        });

        menu3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu3MouseClicked(evt);
            }
        });

        menu4.setToolTipText("");
        menu4.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);
        menu4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu4MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(menu1NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(44, 44, 44)
                                .addComponent(menu2NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(38, 38, 38)
                                .addComponent(menu3NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(menu4NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menu1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(menu1NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu2NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(menu3NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(menu4NameAndPrice, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        orderMenu.setBackground(new java.awt.Color(153, 204, 255));
        orderMenu.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        orderMenu.setText("주문하기");
        orderMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderMenuActionPerformed(evt);
            }
        });

        koreanFood.setBackground(new java.awt.Color(204, 255, 255));
        koreanFood.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        koreanFood.setText("한식");
        koreanFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        koreanFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                koreanFoodActionPerformed(evt);
            }
        });

        japaneseFood.setBackground(new java.awt.Color(204, 255, 255));
        japaneseFood.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        japaneseFood.setText("일식");
        japaneseFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        japaneseFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                japaneseFoodActionPerformed(evt);
            }
        });

        chineseFood.setBackground(new java.awt.Color(204, 255, 255));
        chineseFood.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        chineseFood.setText("중식");
        chineseFood.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        chineseFood.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chineseFoodActionPerformed(evt);
            }
        });

        drinkMenu.setBackground(new java.awt.Color(204, 255, 255));
        drinkMenu.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        drinkMenu.setText("음료");
        drinkMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        drinkMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drinkMenuActionPerformed(evt);
            }
        });

        allMenu.setBackground(new java.awt.Color(153, 204, 255));
        allMenu.setFont(new java.awt.Font("HY목각파임B", 1, 18)); // NOI18N
        allMenu.setText("모든 메뉴");
        allMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        allMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                allMenuActionPerformed(evt);
            }
        });

        orderedMenu.setBackground(new java.awt.Color(153, 204, 255));
        orderedMenu.setFont(new java.awt.Font("HY목각파임B", 1, 18)); // NOI18N
        orderedMenu.setText("주문 내역");
        orderedMenu.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        orderedMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderedMenuActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("HY목각파임B", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("인하 휴게소");

        lblTotalPay.setFont(new java.awt.Font("한컴산뜻돋움", 1, 14)); // NOI18N
        lblTotalPay.setText("총        액  :");

        lblSelectedMenu.setFont(new java.awt.Font("한컴산뜻돋움", 1, 14)); // NOI18N
        lblSelectedMenu.setText("담은 메뉴  :");

        totalPay.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(allMenu, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(orderedMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(koreanFood, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addComponent(chineseFood, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(japaneseFood, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(32, 32, 32)
                        .addComponent(drinkMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblSelectedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(selectedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblTotalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(totalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(38, 38, 38)
                        .addComponent(orderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(koreanFood, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(chineseFood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(japaneseFood, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(drinkMenu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(allMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(orderedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblSelectedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(selectedMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(8, 8, 8)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTotalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(totalPay, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(orderMenu, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void koreanFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_koreanFoodActionPerformed
    
    ImageIcon icon1 = new ImageIcon(getClass().getResource("/bibimbap.jpg"));
    ImageIcon icon2 = new ImageIcon(getClass().getResource("/kimchijjigae.jpg"));
    ImageIcon icon3 = new ImageIcon(getClass().getResource("/jeyuk.jpg"));
    ImageIcon icon4 = new ImageIcon(getClass().getResource("/bulgogi.jpg"));
    // 이미지 크기를 JLabel의 크기에 맞게 조정
    Image image1 = icon1.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_DEFAULT);
    Image image2 = icon2.getImage().getScaledInstance(menu2.getWidth(), menu2.getHeight(), Image.SCALE_DEFAULT);
    Image image3 = icon3.getImage().getScaledInstance(menu3.getWidth(), menu3.getHeight(), Image.SCALE_DEFAULT);
    Image image4 = icon4.getImage().getScaledInstance(menu4.getWidth(), menu4.getHeight(), Image.SCALE_DEFAULT);
    
    ImageIcon scaledIcon1 = new ImageIcon(image1);
    ImageIcon scaledIcon2 = new ImageIcon(image2);
    ImageIcon scaledIcon3 = new ImageIcon(image3);
    ImageIcon scaledIcon4 = new ImageIcon(image4);
    
    // 각각의 JLabel에 이미지 및 텍스트 설정
    
    menu1.setIcon(scaledIcon1);
    menu1NameAndPrice.setText("비빔밥 7000원");
    
    menu2.setIcon(scaledIcon2);
    menu2NameAndPrice.setText("제육볶음 7500원");

    menu3.setIcon(scaledIcon3);
    menu3NameAndPrice.setText("김치찌개 6500원");

    menu4.setIcon(scaledIcon4);
    menu4NameAndPrice.setText("불고기 7500원");
    
    
    
    }//GEN-LAST:event_koreanFoodActionPerformed

    private void chineseFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chineseFoodActionPerformed
        // TODO add your handling code here:
    ImageIcon icon1 = new ImageIcon(getClass().getResource("/jjajang.jpg"));
    ImageIcon icon2 = new ImageIcon(getClass().getResource("/jjambbong.jpg"));
    ImageIcon icon3 = new ImageIcon(getClass().getResource("/friedrice.jpg"));
    ImageIcon icon4 = new ImageIcon(getClass().getResource("/tangsuyuk.jpg"));
    
    // 이미지 크기를 JLabel의 크기에 맞게 조정
    Image image1 = icon1.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_DEFAULT);
    Image image2 = icon2.getImage().getScaledInstance(menu2.getWidth(), menu2.getHeight(), Image.SCALE_DEFAULT);
    Image image3 = icon3.getImage().getScaledInstance(menu3.getWidth(), menu3.getHeight(), Image.SCALE_DEFAULT);
    Image image4 = icon4.getImage().getScaledInstance(menu4.getWidth(), menu4.getHeight(), Image.SCALE_DEFAULT);

    ImageIcon scaledIcon1 = new ImageIcon(image1);
    ImageIcon scaledIcon2 = new ImageIcon(image2);
    ImageIcon scaledIcon3 = new ImageIcon(image3);
    ImageIcon scaledIcon4 = new ImageIcon(image4);
    
    // 각각의 JLabel에 이미지 및 텍스트 설정
    
    menu1.setIcon(scaledIcon1);
    menu1NameAndPrice.setText("짜장면 6000원");
    
    menu2.setIcon(scaledIcon2);
    menu2NameAndPrice.setText("짬뽕 6000원");

    menu3.setIcon(scaledIcon3);
    menu3NameAndPrice.setText("볶음밥 6000원");

    menu4.setIcon(scaledIcon4);
    menu4NameAndPrice.setText("탕수육 12000원");


    }//GEN-LAST:event_chineseFoodActionPerformed

    private void japaneseFoodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_japaneseFoodActionPerformed
        // TODO add your handling code here:
        
    ImageIcon icon1 = new ImageIcon(getClass().getResource("/ramen.jpg"));
    ImageIcon icon2 = new ImageIcon(getClass().getResource("/donkkaseu.jpg"));
    ImageIcon icon3 = new ImageIcon(getClass().getResource("/chobab.jpg"));
    ImageIcon icon4 = new ImageIcon(getClass().getResource("/donburi.jpg"));
    // 이미지 크기를 JLabel의 크기에 맞게 조정
    Image image1 = icon1.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_DEFAULT);
    Image image2 = icon2.getImage().getScaledInstance(menu2.getWidth(), menu2.getHeight(), Image.SCALE_DEFAULT);
    Image image3 = icon3.getImage().getScaledInstance(menu3.getWidth(), menu3.getHeight(), Image.SCALE_DEFAULT);
    Image image4 = icon4.getImage().getScaledInstance(menu4.getWidth(), menu4.getHeight(), Image.SCALE_DEFAULT);
    
    ImageIcon scaledIcon1 = new ImageIcon(image1);
    ImageIcon scaledIcon2 = new ImageIcon(image2);
    ImageIcon scaledIcon3 = new ImageIcon(image3);
    ImageIcon scaledIcon4 = new ImageIcon(image4);
    
    // 각각의 JLabel에 이미지 및 텍스트 설정
    
    menu1.setIcon(scaledIcon1);
    menu1NameAndPrice.setText("라멘 7000원");
    
    menu2.setIcon(scaledIcon2);
    menu2NameAndPrice.setText("돈까스 7500원");

    menu3.setIcon(scaledIcon3);
    menu3NameAndPrice.setText("초밥 9000원");

    menu4.setIcon(scaledIcon4);
    menu4NameAndPrice.setText("돈부리 7500원");
    }//GEN-LAST:event_japaneseFoodActionPerformed

    private void menu1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu1MouseClicked
        // TODO add your handling code here:
        addMenuToSelectedMenu(menu1NameAndPrice.getText());
        addPriceToTotalPay(menu1NameAndPrice.getText());
    }//GEN-LAST:event_menu1MouseClicked

    private void menu2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu2MouseClicked
        // TODO add your handling code here:
        addMenuToSelectedMenu(menu2NameAndPrice.getText());
        addPriceToTotalPay(menu2NameAndPrice.getText());
    }//GEN-LAST:event_menu2MouseClicked

    private void menu3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu3MouseClicked
        // TODO add your handling code here:
        addMenuToSelectedMenu(menu3NameAndPrice.getText());
        addPriceToTotalPay(menu3NameAndPrice.getText());
    }//GEN-LAST:event_menu3MouseClicked

    private void menu4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu4MouseClicked
        // TODO add your handling code here:
        addMenuToSelectedMenu(menu4NameAndPrice.getText());
        addPriceToTotalPay(menu4NameAndPrice.getText());
    }//GEN-LAST:event_menu4MouseClicked

    private void allMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_allMenuActionPerformed
         // Create a new JFrame
    JFrame allMenuFrame = new JFrame("전체 메뉴");

    // Create a panel to hold the menu items
    JPanel menuPanel = new JPanel(new GridLayout(0, 2)); // 2열로 배열 

    // Add menu items to the panel
    addMenuItem(menuPanel, "비빔밥", "7000원", "/bibimbap.jpg");
    addMenuItem(menuPanel, "제육볶음", "7500원", "/jeyuk.jpg");
    addMenuItem(menuPanel, "김치찌개", "6500원", "/kimchijjigae.jpg");
    addMenuItem(menuPanel, "불고기", "7500원", "/bulgogi.jpg");
    addMenuItem(menuPanel, "짜장", "6000원", "/jjajang.jpg");
    addMenuItem(menuPanel, "짬뽕", "6000원", "/jjambbong.jpg");
    addMenuItem(menuPanel, "볶음밥", "6000원", "/friedrice.jpg");
    addMenuItem(menuPanel, "탕수육", "12000원", "/tangsuyuk.jpg");
    addMenuItem(menuPanel, "라멘", "7000원", "/ramen.jpg");
    addMenuItem(menuPanel, "돈까스", "7500원", "/donkkaseu.jpg");
    addMenuItem(menuPanel, "초밥", "9000원", "/chobab.jpg");
    addMenuItem(menuPanel, "돈부리", "7500원", "/donburi.jpg");
    addMenuItem(menuPanel, "콜라", "2000원", "/coke.jpg");
    addMenuItem(menuPanel, "사이다", "2000원", "/cider.jpg");
    addMenuItem(menuPanel, "환타오렌지", "2000원", "/fantaOrange.jpg");
    addMenuItem(menuPanel, "환타포도", "2000원", "/fantaGrape.jpg");
    
    // ... Add more menu items as needed

    // Add the menu panel to the JFrame
    allMenuFrame.add(menuPanel);

    // Set size and make it visible
    allMenuFrame.setSize(938, 611);
    allMenuFrame.setVisible(true);
       
   
    }//GEN-LAST:event_allMenuActionPerformed
    
    private void drinkMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drinkMenuActionPerformed
        // TODO add your handling code here:
    ImageIcon icon1 = new ImageIcon(getClass().getResource("/coke.jpg"));
    ImageIcon icon2 = new ImageIcon(getClass().getResource("/cider.jpg"));
    ImageIcon icon3 = new ImageIcon(getClass().getResource("/fantaOrange.jpg"));
    ImageIcon icon4 = new ImageIcon(getClass().getResource("/fantaGrape.jpg"));
    // 이미지 크기를 JLabel의 크기에 맞게 조정
    Image image1 = icon1.getImage().getScaledInstance(menu1.getWidth(), menu1.getHeight(), Image.SCALE_DEFAULT);
    Image image2 = icon2.getImage().getScaledInstance(menu2.getWidth(), menu2.getHeight(), Image.SCALE_DEFAULT);
    Image image3 = icon3.getImage().getScaledInstance(menu3.getWidth(), menu3.getHeight(), Image.SCALE_DEFAULT);
    Image image4 = icon4.getImage().getScaledInstance(menu4.getWidth(), menu4.getHeight(), Image.SCALE_DEFAULT);
    
    ImageIcon scaledIcon1 = new ImageIcon(image1);
    ImageIcon scaledIcon2 = new ImageIcon(image2);
    ImageIcon scaledIcon3 = new ImageIcon(image3);
    ImageIcon scaledIcon4 = new ImageIcon(image4);
    
    // 각각의 JLabel에 이미지 및 텍스트 설정
    
    menu1.setIcon(scaledIcon1);
    menu1NameAndPrice.setText("콜라 2000원");
    
    menu2.setIcon(scaledIcon2);
    menu2NameAndPrice.setText("사이다 2000원");

    menu3.setIcon(scaledIcon3);
    menu3NameAndPrice.setText("환타오렌지 2000원");

    menu4.setIcon(scaledIcon4);
    menu4NameAndPrice.setText("환타포도 2000원");
    }//GEN-LAST:event_drinkMenuActionPerformed

    private void orderMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderMenuActionPerformed
         // Show confirmation dialog
    int result = JOptionPane.showConfirmDialog(this, "정말 주문하시겠습니까?", "주문 확인", JOptionPane.YES_NO_OPTION);

    // Check the user's choice
    if (result == JOptionPane.YES_OPTION) {
        // User clicked "Yes", perform order-related actions here
        // 예를 들어 주문 내역에 추가하는 등의 동작을 수행할 수 있습니다.
        JOptionPane.showMessageDialog(this, "주문이 완료되었습니다. 감사합니다!", "주문 완료", JOptionPane.INFORMATION_MESSAGE);
        toOrderingFrame(); 
        //주문이 완료되면 필드 초기화
        resetOrderDetails();
    } else {
        // User clicked "No" or closed the dialog
        JOptionPane.showMessageDialog(this, "주문이 취소되었습니다.", "주문 취소", JOptionPane.INFORMATION_MESSAGE);
    }
    }//GEN-LAST:event_orderMenuActionPerformed

    
    //added author SinHyeonWoo
    private void orderedMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderedMenuActionPerformed
        // TODO add yoursad handling code here:
        new OrderedFrame().setVisible(true);
    }//GEN-LAST:event_orderedMenuActionPerformed

    private void toOrderingFrame(){
        new OrderingFrame().setVisible(true);
        OrderingFrame.Instance.getOrderData(selectedMenu.getText());
    };
    

    
  
    //end added by SinHyeonWoo
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton allMenu;
    private javax.swing.JButton chineseFood;
    private javax.swing.JButton drinkMenu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton japaneseFood;
    private javax.swing.JButton koreanFood;
    private javax.swing.JLabel lblSelectedMenu;
    private javax.swing.JLabel lblTotalPay;
    private javax.swing.JLabel menu1;
    private javax.swing.JLabel menu1NameAndPrice;
    private javax.swing.JLabel menu2;
    private javax.swing.JLabel menu2NameAndPrice;
    private javax.swing.JLabel menu3;
    private javax.swing.JLabel menu3NameAndPrice;
    private javax.swing.JLabel menu4;
    private javax.swing.JLabel menu4NameAndPrice;
    private javax.swing.JButton orderMenu;
    private javax.swing.JButton orderedMenu;
    private javax.swing.JTextField selectedMenu;
    private javax.swing.JTextField totalPay;
    // End of variables declaration//GEN-END:variables
}
