
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Font;
import java.awt.GridLayout;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JPanel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author ShinHyeonWoo
 */
public class OrderedFrame extends javax.swing.JFrame {
     DB_MAN DBM = new DB_MAN();                                                      //must be taken
    String strForSummary = "Select * from Summary ";
    /**
     * Creates new form OrderedFrame
     */
    public OrderedFrame() {
        initComponents();
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        JPanel menuListPanel = new JPanel(new GridLayout(0, 3));
        menuListPanel.setSize(410, 550);
        menuListPanel.setBackground(Color.white);
        getDBSummaryData(strForSummary,menuListPanel);
        menu_panel.add(menuListPanel);
    }
    
    public final void createSoldLine(JPanel menuPanel,String menu,String sold,String Price){
        // Add menu name and price to the panel
        JPanel itemList = new JPanel(new GridLayout(0, 3));
        JLabel menuLabel = new JLabel(menu);
        JLabel soldLabel = new JLabel(sold);
        JLabel priceLabel = new JLabel(Price);
        menuLabel.setFont(new Font("Serif", Font.PLAIN, 18));
        menuLabel.setHorizontalAlignment(JLabel.LEFT);
        soldLabel.setFont(new Font("Serif", Font.PLAIN, 18));
        soldLabel.setHorizontalAlignment(JLabel.CENTER);
        priceLabel.setFont(new Font("Serif", Font.PLAIN, 18));
        priceLabel.setHorizontalAlignment(JLabel.RIGHT);
        menuPanel.add(menuLabel);
        menuPanel.add(soldLabel);
        menuPanel.add(priceLabel);
    }
    
    public final void getDBSummaryData(String strQuery,JPanel menuPanel){
        try{
            DBM.dbOpen();
            DBM.DB_rs = DBM.DB_stmt.executeQuery(strQuery);
            while(DBM.DB_rs.next()){
                String menu,sold,resultPrice;
                int price;
                menu = " "+new OrderingFrame().menunameToKor(DBM.DB_rs.getString("Menu_name"));
                sold = DBM.DB_rs.getInt("Menu_sold") + "ea";
                price = DBM.DB_rs.getInt("Menu_price") * DBM.DB_rs.getInt("Menu_sold");
                resultPrice = String.format("%,d \u20A9  ",price);
                createSoldLine(menuPanel,menu,sold,resultPrice);
            }
            DBM.DB_rs.close();
        }catch(Exception e){
            System.err.println("DBDATA SQLException : "+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_name = new javax.swing.JLabel();
        lbl_name1 = new javax.swing.JLabel();
        lbl_name2 = new javax.swing.JLabel();
        menu_panel = new javax.swing.JPanel();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbl_name.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lbl_name.setText("메뉴");

        lbl_name1.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lbl_name1.setText("가격");

        lbl_name2.setFont(new java.awt.Font("맑은 고딕", 0, 24)); // NOI18N
        lbl_name2.setText("판매량");

        javax.swing.GroupLayout menu_panelLayout = new javax.swing.GroupLayout(menu_panel);
        menu_panel.setLayout(menu_panelLayout);
        menu_panelLayout.setHorizontalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 413, Short.MAX_VALUE)
        );
        menu_panelLayout.setVerticalGroup(
            menu_panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 552, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(lbl_name)
                        .addGap(111, 111, 111)
                        .addComponent(lbl_name2)
                        .addGap(101, 101, 101)
                        .addComponent(lbl_name1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addComponent(menu_panel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_name)
                    .addComponent(lbl_name1)
                    .addComponent(lbl_name2))
                .addGap(12, 12, 12)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menu_panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OrderedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OrderedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OrderedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OrderedFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OrderedFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_name;
    private javax.swing.JLabel lbl_name1;
    private javax.swing.JLabel lbl_name2;
    private javax.swing.JPanel menu_panel;
    // End of variables declaration//GEN-END:variables
}
